version: '3'

services:
    netdata:
        image: netdata/netdata
        ports:
            - 19999:19999
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro

    nginx:
        build:
            context: nginx/
        container_name: netdata_nginx
        volumes:
            - "./nginx/netdata.conf:/etc/nginx/conf.d/netdata.conf"
        ports:
            - 80:80
            - 443:443
        links:
            - netdata:netdata
        depends_on:
            - netdata
